apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  namespace: clo835-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        version: v1
    spec:
      containers:
      - name: flask-app
        image: my_app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue" 