apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: clo835-app
  labels:
    app: mysql
    version: v1
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    - name: MYSQL_DATABASE
      value: "employees"
    volumeMounts:
    - name: mysql-init
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: mysql-init
    configMap:
      name: mysql-init-script 